import { useMemo } from 'react'
import { archive, type ArchiveItem } from '../data/archive'
import { asset } from '../lib/asset'
import './Strata.css'

interface Era {
  title: string
  blurb: string
}

// Design-archaeology field notes, one per excavated year.
const ERAS: Record<number, Era> = {
  2026: {
    title: 'AI-Native — you are here',
    blurb:
      'Design and code collapsed into one motion. The surface layer: reinterpretations of the strata below, generated by the same studio that shipped the originals.',
  },
  2019: {
    title: 'Product Mode',
    blurb:
      "The dashboard years. Design moved in-house, screens filled with data, and 'make it pop' became 'make it legible.'",
  },
  2017: {
    title: 'Design Systems Dawn',
    blurb:
      'Components, tokens, and Sketch libraries. Sites stopped being pages and became systems.',
  },
  2016: {
    title: 'Peak Agency Polish',
    blurb:
      'Full-bleed heroes, card grids, material shadows. The web learned restraint — then A/B tested it away.',
  },
  2015: {
    title: 'The Framework Era',
    blurb:
      'Bootstrap under everything, parallax over everything, ghost buttons everywhere in between.',
  },
  2014: {
    title: 'Responsive or Die',
    blurb:
      "Google's mobilegeddon loomed. Breakpoints, retina assets, and the death of the fixed 960.",
  },
  2013: {
    title: 'The Flat Reformation',
    blurb:
      'iOS 7 dropped and the shadows vanished overnight. Hero images, one-pagers, infinite scroll.',
  },
  2012: {
    title: "Skeuomorphism's Last Stand",
    blurb:
      "Stitched leather, wood grain, wet-floor reflections. If it didn't look touchable, it didn't ship.",
  },
  2011: {
    title: 'The jQuery Baroque',
    blurb:
      'Sliders on sliders, lightboxes, corner ribbons. Flash was dying and JavaScript was dancing on the grave.',
  },
  2009: {
    title: 'The Hand-Sliced Web',
    blurb:
      'Photoshop comps sliced into tables, IE7 hacks, 960 pixels of certainty. Every site began as a PSD and a prayer.',
  },
}

const ROMAN = ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII', 'IX', 'X', 'XI', 'XII']

interface Layer {
  year: number
  era: Era
  items: ArchiveItem[]
}

function buildLayers(): Layer[] {
  // Surface layer: the 2026 Flips
  const flips: ArchiveItem[] = archive
    .filter((i) => i.flip)
    .map((i) => ({
      src: i.flip!,
      site: `${i.site} — 2026 flip`,
      cat: 'product',
      year: 2026,
    }))

  const byYear = new Map<number, ArchiveItem[]>()
  for (const item of archive) {
    byYear.set(item.year, [...(byYear.get(item.year) ?? []), item])
  }

  const layers: Layer[] = [{ year: 2026, era: ERAS[2026], items: flips }]
  const years = [...byYear.keys()].sort((a, b) => b - a)
  for (const year of years) {
    layers.push({
      year,
      era: ERAS[year] ?? { title: `${year}`, blurb: '' },
      items: byYear.get(year)!,
    })
  }
  return layers
}

/** Sediment tint: cool surface, warming toward aged sepia at the bottom. */
function tint(idx: number, total: number) {
  const p = Math.round((idx / Math.max(total - 1, 1)) * 100)
  return `color-mix(in oklab, #0a0d12 ${100 - p}%, #191106 ${p}%)`
}

export default function Strata({ onOpen }: { onOpen: (item: ArchiveItem) => void }) {
  const layers = useMemo(buildLayers, [])

  return (
    <div className="strata" aria-label="The archive as geological strata, newest at the surface">
      <p className="mono strata-hint">surface · scroll down to dig ↓</p>
      {layers.map((layer, i) => (
        <section
          key={layer.year}
          className="stratum"
          style={{ background: tint(i, layers.length) }}
        >
          <div className="stratum-rail">
            <span className="mono stratum-roman">Stratum {ROMAN[i]}</span>
            <b className="stratum-year">{layer.year}</b>
            <span className="mono stratum-depth">
              {layer.year === 2026 ? 'surface' : `−${2026 - layer.year} yr`}
            </span>
            <span className="mono stratum-count">
              {layer.items.length} specimen{layer.items.length === 1 ? '' : 's'}
            </span>
          </div>
          <div className="stratum-body">
            <h3>{layer.era.title}</h3>
            <p className="stratum-blurb">{layer.era.blurb}</p>
            <div className="stratum-row">
              {layer.items.map((item, j) => (
                <button
                  key={item.src}
                  className={`specimen ${j % 2 ? 'specimen-tilt-a' : 'specimen-tilt-b'}`}
                  onClick={() => onOpen(item)}
                  aria-label={`${item.site}, ${item.year}`}
                  title={item.site}
                >
                  <img src={asset(item.src)} alt={item.site} loading="lazy" decoding="async" />
                </button>
              ))}
            </div>
          </div>
        </section>
      ))}
      <p className="mono strata-bedrock">bedrock · before 2009 there was print</p>
    </div>
  )
}
